# Generated by Django 3.0.4 on 2020-03-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20200327_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['last_modified']},
        ),
    ]
