# Generated by Django 3.0.4 on 2020-03-29 13:14

from django.db import migrations, models
import django.db.models.deletion
import note.models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20200328_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=note.models.user_directory_path)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Note')),
            ],
        ),
    ]
